Feat(Auth): Adding Authentication and Callbacks
coretech/n2p-api-docs pull request #50
Opened 2021-11-19 21:25 UTC by SuzyNakayama1

- added callbacks for subscription (and deleted webhooks folder from apis)
- added check in build-spec to double check if the webhooks folder exists, if it doesn’t return
- added authentication using password flow
- added security schemes for password flow
- added deprecated to `/cdrs/`

2021-11-30 07:39 UTC, konstantin-smolyakov-idt commented on references/apis/paths/authentication.v1.yaml
> +        - $ref: "#components/parameters/response_type"
**question** Why is the slash removed? I've always used the previous version of `#/components/...`

2021-11-30 07:39 UTC, konstantin-smolyakov-idt commented on references/apis/paths/authentication.v1.yaml
**question** I've expected all authentication paths to be removed in favor of OpenAPI "oauth" mechanism which is a much better way to do this and standard compliant. Why do we still keep it?

2021-11-30 14:06 UTC, SuzyNakayama1 commented on references/apis/paths/authentication.v1.yaml
> +        - $ref: "#components/parameters/response_type"
VSCode keeps complaining about the slashes, showing as error. So I removed and it worked either way, so I decided to delete from all of them.

2021-11-30 14:07 UTC, SuzyNakayama1 commented on references/apis/paths/authentication.v1.yaml
This is from because I started this branch from dev(master). In the documentation branch we will delete this.

2021-11-30 14:13 UTC, konstantin-smolyakov-idt commented on references/apis/paths/authentication.v1.yaml
> +        - $ref: "#components/parameters/response_type"
It sounds like a bug in VSCode or some plugin you are using there. I would suggest to leave it as is.

2021-11-30 14:14 UTC, konstantin-smolyakov-idt commented on references/apis/paths/authentication.v1.yaml
I see, it's fine then.

2021-11-30 20:00 UTC, SuzyNakayama1 commented on references/apis/paths/authentication.v1.yaml
> +        - $ref: "#components/parameters/response_type"
done

2021-12-01 15:24 UTC, konstantin-smolyakov-idt commented on references/apis/paths/authentication.v1.yaml
> +        - $ref: "#components/parameters/response_type"
I can't resolve the thread for some reason, but thanks!

2021-12-02 13:29 UTC, konstantin-smolyakov-idt requested changes

2021-12-02 13:29 UTC, konstantin-smolyakov-idt commented on references/apis/securitySchemes/oauth2.v1.yaml
> +password:
**suggestion (non blocking)** Technically, more than just password is possible. E.g. we can make `implicit` flow working with this app, I beleive. So we should rather name it something like `versatureOAuth`. 

```suggestion
versatureOAuth:
```

2021-12-02 13:29 UTC, konstantin-smolyakov-idt commented on specs/apis.v1.json
> +      "Authorization": {
**suggestion (blocking)** I've never seen `Authorization` header to be used when `securityScheme` is defined. The `OAuth` already implies that the bearer token can be used, so we shouldn't really describe the header. Especially the `enum` restriction that only allows one possible string there.

2021-12-03 07:42 UTC, konstantin-smolyakov-idt commented on references/apis/securitySchemes/oauth2.v1.yaml
> +password:
I see this is fixed, can't resolve the thread because I don't have write permissions to this repo.

2021-12-03 07:43 UTC, konstantin-smolyakov-idt commented on references/apis/paths/webhooks.v1.yaml
> +          application/json:
**question (non blocking)** How will this display for the end user? Will they be able to understand they need to use a specific `vnd.integrate` version?

2021-12-15 07:46 UTC, konstantin-smolyakov-idt requested changes
I see that this repo uses `yarn.lock`, so please remove `package-lock.json`. It was probably generated unintentionally.

2021-12-21 15:52 UTC, merged